### ISSUE TITLE
Support for install via USB-storage

### ISSUE THREAD

**Issue by bittorf** [amooma/GS4#4]
it was a pain to organize / connect a CD-ROM drive to our embedded system only for installing the stuff.
please provide also an image for an USB-key... (it's faster anyway...)

**Comment by wintermeyer** [comment]
Thank you for the input. I put it on the wishlist for version 5.0.

**Comment by saschadaniels** [comment]
Just use a tool like unetbootin to put the image onto the stick.

http://unetbootin.sourceforge.net/

Runs on all platforms.

**Comment by bittorf** [comment]
Good catch - thank you!
